### PR TITLE
NAN 1.5 WIP

### PR DESCRIPTION
**Pull request by kkoopa**
This branch will become NAN 1.5.
Added Asyncworker #207 and new NanNew #210. Needs more testing with actual addons.
Now split into many files. Seems to work so far. Good news for nauv.h

### CODE REVIEW

**Comment by rvagg** [comment]
@kesla let's get this out, io.js@1.0.0 is about to be released so let's sync with that. If you need any help with release process let me know!

**Comment by kesla** [comment]
I guess you meant pinging @kkoopa?

**Comment by rvagg** [comment]
derp, yes, sorry @kesla, you were the first name to pop up, @kkoopa was who I meant

**Comment by kkoopa** [comment]
What about the functions moved from v8::V8 to v8::Isolate? We'll have to do a 1.6 very soon otherwise to cover the v8 discrepancies.

**Comment by rvagg** [comment]
what version of V8 is that in? io.js will be on 3.31 for a while I think, we were burnt already with changes to ES6 classes and their announced removal for 3.31 before it goes final so it's likely there will be a bit of conservatism for the next month or two at least.

**Comment by kkoopa** [comment]
3.29 perhaps... Not quite sure. It's later than what's in 0.11.14, but in joyent/0.12 branch as of now and whatever is used in atom-shell nowadays. I specifically know of the previously mentioned ContextDisposedNotification and I planned on getting it fixed in this release. It's a small addition, but should look through all other functions too to see what else has moved.

Regarding cutting a release, it went quite well last time, apart from npmjs not receiving README.md properly for reasons unknown to me. Maybe due to having an old npm client. I have since updated npm. Any ideas what happened there?

I can push a release out in the morning, say in 10-12 hours. Would like 12 more to tie up these loose ends and avoid releasing 1.5 only to follow with 1.6 a couple days later. How does that sound?

**Comment by rvagg** [comment]
re npm, I have no idea, npm looks at .npmignore if it exists, .gitignore otherwise, then it looks at the files on disk and packages those. If you have the problem again, just do a patch release, no big deal to do patch releases to paper over publish problems.

timing is fine by me, whatever works for you, just expect people to start filing bugs against projects, and NAN, for io.js support today.

**Comment by kkoopa** [comment]
What's with the failed build due to bad node-gyp checksum?
Can you add docker tests for io.js here?

**Comment by rvagg** [comment]
odd error from travis, I have some work to do to make dnt io.js compatible yet but I can have a go

**Comment by rvagg** [comment]
initial results:

```
$ dnt
node@v0.10.34: PASS wrote output to /tmp/nan-dnt-v0.10.34.out
node@v0.11.14: PASS wrote output to /tmp/nan-dnt-v0.11.14.out
iojs@v1.0.1-release: PASS wrote output to /tmp/nan-dnt-v1.0.1-release.out
Took 24s to run 3 versions of Node
```

io.js supporting branch of dnt is https://github.com/rvagg/dnt/pull/14

I don't have images built for the other Node versions we should be testing but I'll start that build process not, I just doubt it'll all be done before I have to go to bed. I'm confident with the above results, no warnings or anything in that output file, very clean. I'm :+1: on a release.

**Comment by kkoopa** [comment]
Good, good. I'll push it out like this when I get home then. Just have to 
update the changelog. Those other changes I listed get to wait until 1.6, in a 
week or two. They are quite minor.

**Comment by rvagg** [comment]
```
node@v0.11.14: PASS wrote output to /tmp/nan-dnt-v0.11.14.out
node@v0.10.34: PASS wrote output to /tmp/nan-dnt-v0.10.34.out
node@v0.11.13: PASS wrote output to /tmp/nan-dnt-v0.11.13.out
node@v0.10.33: PASS wrote output to /tmp/nan-dnt-v0.10.33.out
node@v0.10.32: PASS wrote output to /tmp/nan-dnt-v0.10.32.out
node@v0.10.30: PASS wrote output to /tmp/nan-dnt-v0.10.30.out
node@v0.10.31: PASS wrote output to /tmp/nan-dnt-v0.10.31.out
node@v0.10.29: PASS wrote output to /tmp/nan-dnt-v0.10.29.out
node@v0.10.28: PASS wrote output to /tmp/nan-dnt-v0.10.28.out
node@v0.10.26: PASS wrote output to /tmp/nan-dnt-v0.10.26.out
node@v0.10.25: PASS wrote output to /tmp/nan-dnt-v0.10.25.out
node@v0.10.24: PASS wrote output to /tmp/nan-dnt-v0.10.24.out
node@v0.10.22: PASS wrote output to /tmp/nan-dnt-v0.10.22.out
node@v0.10.23: PASS wrote output to /tmp/nan-dnt-v0.10.23.out
node@v0.10.21: PASS wrote output to /tmp/nan-dnt-v0.10.21.out
node@v0.10.20: PASS wrote output to /tmp/nan-dnt-v0.10.20.out
node@v0.10.19: PASS wrote output to /tmp/nan-dnt-v0.10.19.out
node@v0.8.28 : PASS wrote output to /tmp/nan-dnt-v0.8.28.out
node@v0.8.27 : PASS wrote output to /tmp/nan-dnt-v0.8.27.out
node@v0.8.26 : PASS wrote output to /tmp/nan-dnt-v0.8.26.out
node@v0.8.24 : PASS wrote output to /tmp/nan-dnt-v0.8.24.out
iojs@v1.0.1-release: PASS wrote output to /tmp/nan-dnt-v1.0.1-release.out
Took 113s to run 22 versions of Node
```

**Comment by kkoopa** [comment]
Nice, very nice indeed.

**Comment by rvagg** [comment]
agreed, well done @kkoopa!

**Pull request merged**
