### PR TITLE
Remove support for signatures with arguments

### PR DESCRIPTION
**Pull request by kkoopa**
See #308

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Untested but LGTM

**Comment by zcbenz** [comment]
Can you publish a release that contains this fix? The latest [electron](https://github.com/atom/electron) release has been published with Chrome42, and nan@1.7.0 unfortunately is not compatible with it, however the master branch of nan with this fix works perfectly.

**Comment by kkoopa** [comment]
Sure, I can publish sometime within the following 12 hours.

**Comment by kkoopa** [comment]
Done

**Comment by zcbenz** [comment]
Awesome, thanks!

**Pull request merged**
