### PR TITLE
NAN 1.6

### PR DESCRIPTION
**Pull request by kkoopa**
* Added new functions to deal with functions moved from V8 to Isolate. See #225.
* Deprecated `NanNewContextHandle` in favor of `NanNew<Context>`.
* Add support for node::Encode/DecodeBytes/DecodeWrite

### CODE REVIEW

**Comment by kkoopa** [comment]
This will not work with node webkit, as they have updated v8, but not indicated it in any detectable way as far as I can see. Too bad.

**Comment by rvagg** [comment]
@rogerwang is there someone in particular we should pull in for this? nw.js could lose solid native addon support if we can't find a resolution to this.

**Comment by kkoopa** [comment]
#226 is related for slightly different reasons

**Comment by rogerwang** [comment]
I'll help to fix this. What do I need to do in nw.js? defining NODE_MODULE_VERSION to some value?

**Comment by rvagg** [comment]
@kkoopa do we a good have a recommendation here?

@rogerwang if your ABI is the same as some io.js or node release then match the `NODE_MODULE_VERSION` to that, otherwise make it significantly different. io.js is at 42, atom has jumped to [100](https://github.com/atom/node/commit/83f1b415e95e4d47e70c1cd064fdf153fc65fc47). Another alternative is to introduce a new define we can pick up on that talks to your ABI version.

**Comment by rogerwang** [comment]
It should be the same as io.js. I'll update the io.js in nw.js, so it will be 42. Currently it's some old version (1.0.0).

**Comment by kkoopa** [comment]
Ah, that would of course explain the mismatch. io.js only bumped `NODE_MODULE_VERSION` at the last minute before release. Everything should be alright after updating.

**Comment by Mithgol** [comment]
NW.js v0.12.0-alpha3 was [released](https://groups.google.com/forum/#!topic/nwjs-general/heM9DRTLx5U) ≈8 hours ago.

Its inner Chromium is updated to 41 beta (41.0.2272.32) and io.js is updated to v1.2.0.

Does that mean nan support?

**Comment by kkoopa** [comment]
I guess so.

**Pull request merged**
