### PR TITLE
Add porting guide to readme

### PR DESCRIPTION
**Pull request by hgupta9**
Add a section that explains how to modify C++ code for NAN.

<table><tbody>

<tr><th>Aspect</th><th>Without NAN</th><th>With NAN</th></tr>

<tr><td>Function declaration</td><td><pre>class MyClass : ObjectWrap {
    ....
    static Handle<Value> ToString(const Arguments& args);
    ....
}</pre></td></th><td><pre>class MyClass : ObjectWrap {
    ....
    static NAN_METHOD(ToString);
    ....
}</pre></td></tr>

<tr><td>Function definition</td><td><pre>Handle<Value>
MyClass::ToString(const Arguments& args)
{
	HandleScope scope;
	....
}</pre></td></th><td><pre>
NAN_METHOD(MyClass::ToString)
{
  NanScope();
  ....
}</pre></td></tr>

<tr><td>Return a value</td><td><pre>return scope.Close(result);</pre></td></th><td><pre>NanReturnValue(result);</pre></td></tr>

<tr><td>Return undefined</td><td><pre>return Undefined();</pre></td></th><td><pre>NanReturnUndefined();</pre></td></tr>

<tr><td>Throw an error</td><td><pre>return ThrowException(
  Exception::Error(
    String::New("Error text...")));</pre></td></th><td><pre>NanThrowError("Error text...");</pre></td></tr>

<tr><td>New v8 string literal</td><td><pre>String::NewSymbol("my text")</pre></td></th><td><pre>NanNew("my text")</pre></td></tr>

</tbody></table>

### CODE REVIEW

**Comment by hgupta9** [comment]
@rvagg - Can you add this in? Is there a problem or are we waiting for other contributors to green light this PR?

**Comment by kkoopa** [comment]
Ah, I apologize. Lost track of this. Will merge.

**Comment by hgupta9** [comment]
Have you guys deleted this content? I cannot find it anymore in the readme.

**Comment by kkoopa** [comment]
It was cut in the transition to NAN 2, since the API changes meant it was no longer current.

**Pull request merged**
