### PR TITLE
Replicate issue #239 by testing node-webkit on travis

### PR DESCRIPTION
**Pull request by springmeyer**

### CODE REVIEW

**Comment by springmeyer** [comment]
replicated at Line 323: https://travis-ci.org/rvagg/nan/jobs/47320440#L323

**Comment by rvagg** [comment]
neato, +1 from me then

**Comment by kkoopa** [comment]
Something is broken here. Modules don't seem to register, as if there's a strange mix of versions somewhere.
https://travis-ci.org/rvagg/nan/jobs/47439294

**Comment by rvagg** [comment]
```
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.32 | linux | x64
gyp info chdir test
gyp http GET http://node-webkit.s3.amazonaws.com/v0.11.5/nw-headers-v0.11.5.tar.gz
```

it's compiling against 0.11.5 headers even though it's on 0.10.32. @springmeyer any hints here? Do you use node-webkit?

**Pull request merged**
