### PR TITLE
Add details to readme on how to run tests

### PR DESCRIPTION
**Pull request by springmeyer**
Hopefully I got this right.

### CODE REVIEW

**Comment by kkoopa** [comment]
make test works wonders if gnu make is available

**Comment by rvagg** [comment]
@springmeyer I'd put `make test` as an alternative way to run them, I think you can keep what you have there as well

**Comment by springmeyer** [comment]
haha, totally did not see the Makefile. Running `make test` though does not find node-gyp for me in the local `node_modules/.bin`:

```
$ make test
cd test/ && node-gyp rebuild
/bin/sh: node-gyp: command not found
make: *** [test/build/Release/symbols.node] Error 127
```

**Comment by rvagg** [comment]
yeah, it's designed for a certain kind of workflow which assumes a global node-gyp and that may not be ideal for casual contributors .. FYI in .dntrc I do this which is different again:

```
  npm install && \
  node_modules/.bin/node-gyp --nodedir /usr/src/node/ rebuild --directory test && \
  node_modules/.bin/tap --gc test/js/*-test.js
```

**Comment by kkoopa** [comment]
Won't this break make test if I don't have a locally installed node-gyp?

**Pull request merged**
