### PR TITLE
Support atom-shell 0.21

### PR DESCRIPTION
**Pull request by kkoopa**
This should get atom-shell working again.
Addresses #226.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM but perhaps consider breaking out the number literals into defines.

**Comment by kkoopa** [comment]
Aye

**Comment by bnoordhuis** [comment]
LGTM

**Comment by zcbenz** [comment]
:sparkling_heart:

**Comment by maxkorp** [comment]
Awesome! What's the timeline for this making it into a release?
I've tested building [nodegit](github.com/nodegit/nodegit) for atom shell 0.21 against nan@master and it works, but we'd like to avoid versioning against a specific sha. We're not planning on releasing for another week or two at least probably, so its not super urgent, but I know 2.0 is slated as vNext and I imagine that taking a while potentially. If it's not gonna take a long time then nevermind, but if it's gonna be a month or two, any chance of a dot release?

**Comment by johnhaley81** [comment]
:+1: :)

**Comment by kkoopa** [comment]
No worries. I'll still put out master as 1.7.0 within a week or two. After that, things should hopefully stabilize for a while so we can work on 2.0.

**Comment by maxkorp** [comment]
Sweet, thanks!

**Comment by johnhaley81** [comment]
Hey @kkoopa, just a friendly ping on the status of 1.7.0 :)

**Comment by kkoopa** [comment]
I guess #284 that just came in is the only blocker now that #278 has been sorted out. ETA is around 1 week, in time for March.

**Comment by johnhaley81** [comment]
Sounds great! Thanks for the update.

**Pull request merged**
